# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI test

on:
  schedule:
    - cron: '0 4 * * *'
    #- cron: '0 */8 * * *'
  
  #push:
  #  branches: [ main ]
  pull_request:
    branches: [ main ]

  # Try merging a pull request when it is approved.
  pull_request_review:
    types:
      - submitted

jobs:
  test:
    if: github.event.review.state == 'approved' || !github.event.review
    runs-on: ${{ matrix.os }}
    env:
      ENV: ${{ secrets.ENV }}
      GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
      GMAIL_PWD: ${{ secrets.GMAIL_PWD }}
      JWT_TOKEN_SECRET: ${{ secrets.JWT_TOKEN_SECRET }}
      MONGO_URL: ${{ secrets.MONGO_URL }}
      STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      MONGO_URL_LOCAL: ${{ secrets.MONGO_URL_LOCAL }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [12.x, 14.x, 15.x]
        mongodb-version: [4.2, 4.4]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      #- name: install pm2
      #  run: npm install -g pm2
      - name: install modules deps
        run: npm install
      - name: build if present
        run: npm run build --if-present
      #- name: pm2 kill && pm2 start && pm2 status
      #  run: pm2 kill && pm2 start dist/app.js

      - name: test unit
        run: npm test
      #- name: pm2 kill
      #  run: pm2 kill
